name: "[Test] connect"
on:
  workflow_call:
    inputs:
      methods:
        description: "List of methods to include in tests (example applySettings,applyFlags,getFeatures)"
        type: "string"
        required: false
      test-pattern:
        description: "Test pattern to use (e.g. `init` or `methods`)"
        type: "string"
        required: true
      tests-firmware:
        description: "Firmware version for the tests (example 2-latest, 2.2.0, 2-main)"
        type: "string"
        required: false
        default: "2-latest"

jobs:
  node:
    name: node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn
      # todo: ideally do not install everything. possibly only devDependencies could be enough for testing (if there was not for building libs)?
      - run: sed -i "/\"node\"/d" package.json
      - run: yarn install
      - run: './docker/docker-connect-test.sh node -p "${{ inputs.test-pattern }}" -f ${{ inputs.tests-firmware }} -i ${{ inputs.methods }}'

  web:
    name: web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn
      - run: |
          echo -e "\nenableScripts: false" >> .yarnrc.yml
      # Install dependecies only for @trezor/connect package
      - run: yarn workspaces focus @trezor/connect
      - name: Retrieve build connect-web
        uses: actions/download-artifact@v4
        with:
          name: build-artifact-connect-web
          path: packages/connect-web/build
      - name: Retrieve build connect-iframe
        uses: actions/download-artifact@v4
        with:
          name: build-artifact-connect-iframe
          path: packages/connect-iframe/build
      - run: cd packages/connect-iframe && tree .
      - name: "Echo download path"
        run: echo ${{steps.download.outputs.download-path}}
      - run: './docker/docker-connect-test.sh web -p "${{ inputs.test-pattern }}" -f ${{ inputs.tests-firmware }} -i ${{ inputs.methods }}'
