name: "[Test] suite-native Android E2E"
on:
  push:
    branches:
      - "*"

jobs:
  run_android_e2e:
    timeout-minutes: 90
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Install node and yarn
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Install Yarn dependencies
        run: yarn install

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Prebuild native expo project
        working-directory: ./suite-native/app
        run: yarn prebuild

      - name: Cache Detox build
        id: cache-detox-build
        uses: actions/cache@v3
        with:
          path: android/build
          key: ${{ runner.os }}-detox-build
          restore-keys: |
            ${{ runner.os }}-detox-build

      - name: Detox build
        run: yarn ../../node_modules/.bin/detox build --configuration android.emu.release
        working-directory: ./suite-native/app

      - name: Get device name
        id: device
        run: node -e "console.log('AVD_NAME=' + require('./suite-native/app/.detoxrc').devices.emulator.device.avdName)" >> $GITHUB_OUTPUT

      - name: Detox test
        uses: reactivecircus/android-emulator-runner@v2
        working-directory: ./suite-native/app
        with:
          api-level: 31
          arch: x86_64
          avd-name: ${{ steps.device.outputs.AVD_NAME }}
          script: yarn ../../node_modules/.bin/detox test --configuration android.emu.release --headless --record-logs all
